name: central-authz
run-name: ${{ github.actor }} is testing Repo:Workflow Authorization
on: [push, workflow_dispatch]
jobs:
  debug-token:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: steve-todorov/oidc-debugger-action@b6d83b24a379e77233fb6b26f1c1a662c4bf443c
        with:
          audience: https://pluto.example.com
